name: SpigotTest
version: '1.0-SNAPSHOT'
main: me.tempest.spigotTest.SpigotTest
api-version: '1.21'
authors: [ Commander Tempest ]
description: First Plugin
website: https://stormur.netlify.app/
commands:
  die:
    description: sets sending player's hp to 0
    usage: /<command>
  god:
    description: makes player invulnerable
    usage: /<command>
    permission: spigottest.god
    aliases:
      - invulnerable
      - invincible
      - babydonthurtme
permissions:
  spigottest.god:
    description: the permission that allows you to use the /god command
    default: not op
    children:
      spigottest.die: true
